# Generated by Django 4.1.3 on 2022-11-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
