# Generated by Django 4.1.3 on 2022-11-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
