# Generated by Django 4.1.3 on 2022-11-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_fname_studentregistration_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='txtarea',
            new_name='message',
        ),
    ]
